[package]
edition = "2024"
name = "xpanse-api"
version = "0.2.1"
license = "GPL-3.0"
description = "Shared API for xpanse apps, module drivers, and platform firmware for the hackxpansion console"
documentation = "https://docs.rs/xpanse-api"
repository = "https://github.com/hackclub/hackxpansion"

[package.metadata.docs.rs]
default-target = "thumbv8m.main-none-eabihf"
targets = []

[dependencies]
embassy-futures = { workspace = true }
embassy-rp = { workspace = true }
embassy-time = { workspace = true }
embassy-sync = { workspace = true }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-hal-bus = { workspace = true }
defmt = { workspace = true }
embedded-io-async = { workspace = true }
static_cell = { workspace = true }
libm = { workspace = true }
slint = { workspace = true }
