words = [
    "AVDD",
    "DMA",
    "Effecit",
    "GND",
    "Hackatime",
    "PIO",
    "PIO's",
    "PWM",
    "Pinout",
    "Slint",
    "UART",
    "baudrate",
    "birthdate",
    "bitbang",
    "clk",
    "hackclub",
    "hackxpansion",
    "impls",
    "journaling",
    "kicad",
    "microcontroller",
    "mosi",
    "perfboard",
    "repo's",
    "scl",
    "sda",
    "timelapse",
    "xpanse",
    "xpanse",
]
